### ISSUE TITLE
Generated section in readme

### ISSUE THREAD

**Issue by b00f** [tihu-nlp/tihu-grpc-nodejs-client-example#1]
What is the Generated section in readme?
Is it for generated errors? Do you have any error of using/compiling proto file?

**Comment by shotor** [comment]
It's to generate a js client from the proto file. This is the recommended approach to consume grpc apis and what I want to use in my app too.

Generation goes fine, you can see the results here from two libraries I tried:

- https://github.com/tihu-nlp/tihu-grpc-nodejs-client-example/tree/master/src/protoc-gen-grpc
- https://github.com/tihu-nlp/tihu-grpc-nodejs-client-example/tree/master/src/protoc-gen-ts

But they both throw an error when I try to call the API that you can see in the readme.

I haven't been able to find the cause. I doubt it's the generation itself. Because it's fairly straightforward. There might be a problem with the API, but I have to do some more reading to find out how to test this.

**Comment by shotor** [comment]
everything works in the other repo, I'm going to delete this repo soon and link to the other repo from the tihu main repo
